source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'bson_ext'
gem 'mongo'
gem 'twitter_oauth'
gem 'sinatra-twitter-oauth', require: 'sinatra-twitter-oauth'
gem 'slim'
gem 'sass'
gem 'coffee-script'
gem 'json'

gem 'rb-fsevent'
gem 'rerun'
gem 'debugger'